#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: OTFhMGRmYTRmZWU3ZjJmNTY5NThiMTNmYTNmYTc5YTRiNjQ0ZjA0YTRjZjI1ZjdkNmY0NDNkOWZlNmQ1ZDVjNGUzZmYzNDUzZTNlNDMxMzdjMjRkZTY4MTliMTRlYzc4Y2ZhNw==

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
