version: '2'
services:
#  admin-app:
#    image: admin
#    environment:
#      - _JAVA_OPTIONS=-Xmx512m -Xms256m
#      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
#      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
#      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
#      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
#      - 'SPRING_DATASOURCE_URL=jdbc:mysql://admin-mysql:3306/admin?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true'
#      - JHIPSTER_SLEEP=30
#      - JHIPSTER_REGISTRY_PASSWORD=admin
#    ports:
#      - '8081:8081'
#  admin-mysql:
#    image: 'mysql:8.0.18'
#    environment:
#      - MYSQL_USER=root
#      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
#      - MYSQL_DATABASE=admin
#    ports:
#      - 38081:3306
#    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
#
#  auth-app:
#    image: auth
#    environment:
#      - _JAVA_OPTIONS=-Xmx512m -Xms256m
#      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
#      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
#      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
#      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
#      - 'SPRING_DATASOURCE_URL=jdbc:mysql://auth-mysql:3306/auth?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true'
#      - JHIPSTER_SLEEP=30
#      - JHIPSTER_REGISTRY_PASSWORD=admin
#  auth-mysql:
#    image: 'mysql:8.0.18'
#    environment:
#      - MYSQL_USER=root
#      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
#      - MYSQL_DATABASE=auth
#    ports:
#      - 38092:3306
#    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
#
#  batch-app:
#    image: batch
#    environment:
#      - _JAVA_OPTIONS=-Xmx512m -Xms256m
#      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
#      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
#      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
#      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
#      - 'SPRING_DATASOURCE_URL=jdbc:mysql://batch-mysql:3306/batch?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true'
#      - JHIPSTER_SLEEP=30
#      - JHIPSTER_REGISTRY_PASSWORD=admin
#  batch-mysql:
#    image: 'mysql:8.0.18'
#    environment:
#      - MYSQL_USER=root
#      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
#      - MYSQL_DATABASE=batch
#    ports:
#      - 38096:3306
#    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
#
#  client-app:
#    image: client
#    environment:
#      - _JAVA_OPTIONS=-Xmx512m -Xms256m
#      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
#      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
#      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
#      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
#      - 'SPRING_DATASOURCE_URL=jdbc:mysql://client-mysql:3306/client?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true'
#      - JHIPSTER_SLEEP=30
#      - JHIPSTER_REGISTRY_PASSWORD=admin
#    ports:
#      - '8080:8080'
#  client-mysql:
#    image: 'mysql:8.0.18'
#    environment:
#      - MYSQL_USER=root
#      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
#      - MYSQL_DATABASE=client
#    ports:
#      - 38080:3306
#    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
#
  core-app:
    image: core
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://core-mysql:3306/core?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true'
      - JHIPSTER_SLEEP=30
      - JHIPSTER_REGISTRY_PASSWORD=admin
  core-mysql:
    image: 'mysql:8.0.18'
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=core
    ports:
      - 38091:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp

  main-app:
    image: main
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://main-mysql:3306/main?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true'
      - JHIPSTER_SLEEP=30
      - JHIPSTER_REGISTRY_PASSWORD=admin
  main-mysql:
    image: 'mysql:8.0.18'
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=main
    ports:
      - 38097:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp

#  messaging-app:
#    image: messaging
#    environment:
#      - _JAVA_OPTIONS=-Xmx512m -Xms256m
#      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
#      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
#      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
#      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
#      - 'SPRING_DATASOURCE_URL=jdbc:mysql://messaging-mysql:3306/messaging?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true'
#      - JHIPSTER_SLEEP=30
#      - JHIPSTER_REGISTRY_PASSWORD=admin
#  messaging-mysql:
#    image: 'mysql:8.0.18'
#    environment:
#      - MYSQL_USER=root
#      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
#      - MYSQL_DATABASE=messaging
#    ports:
#      - 38093:3306
#    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
#
#  reports-app:
#    image: reports
#    environment:
#      - _JAVA_OPTIONS=-Xmx512m -Xms256m
#      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
#      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
#      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
#      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
#      - 'SPRING_DATASOURCE_URL=jdbc:mysql://reports-mysql:3306/reports?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true'
#      - JHIPSTER_SLEEP=30
#      - JHIPSTER_REGISTRY_PASSWORD=admin
#  reports-mysql:
#    image: 'mysql:8.0.18'
#    environment:
#      - MYSQL_USER=root
#      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
#      - MYSQL_DATABASE=reports
#    ports:
#      - 38094:3306
#    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
#
#  workflow-app:
#    image: workflow
#    environment:
#      - _JAVA_OPTIONS=-Xmx512m -Xms256m
#      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
#      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
#      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
#      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
#      - 'SPRING_DATASOURCE_URL=jdbc:mysql://workflow-mysql:3306/workflow?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true'
#      - JHIPSTER_SLEEP=30
#      - JHIPSTER_REGISTRY_PASSWORD=admin
#  workflow-mysql:
#    image: 'mysql:8.0.18'
#    environment:
#      - MYSQL_USER=root
#      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
#      - MYSQL_DATABASE=workflow
#    ports:
#      - 38095:3306
#    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp

  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
